jwt:
  secret: ${JWT_SECRET}
  expire: ${JWT_EXPIRE}

project:
  upload:
    path: ${UPLOAD_PATH}
  aes:
    key: ${AES_KEY}

spring:
  application:
    name: spring04
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: be24-s3
      region:
        static: ap-northeast-2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

kakao:
  api:
    key: ${KAKAO_API_KEY}